-- 테이블 및 시퀀스 삭제
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE PERSON_SEQ;

-- 테이블 생성
CREATE TABLE JOB(
    jNO     NUMBER(2),
    jNAME   VARCHAR2(50) NOT NULL,
    PRIMARY KEY(jNO));
    
CREATE TABLE PERSON(
    pNO     NUMBER(5),
    pNAME   VARCHAR2(50) NOT NULL,
    jNO     NUMBER(2) NOT NULL,
    KOR     NUMBER(3) CHECK(KOR >= 0),
    ENG     NUMBER(3) CHECK(ENG >= 0),
    MAT     NUMBER(3) CHECK(MAT >= 0),
    PRIMARY KEY(pNO),
    FOREIGN KEY(jNO) REFERENCES JOB(jNO));

CREATE SEQUENCE PERSON_SEQ
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;
    
-- 데이터 INSERT / 직업 3개
INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');
INSERT INTO JOB VALUES (30, '스태프');
SELECT * FROM JOB;

INSERT INTO PERSON VALUES (PERSON_SEQ.NEXTVAL, '정우성', 10, 90, 80, 81);
INSERT INTO PERSON VALUES (PERSON_SEQ.NEXTVAL, '박세영', 10, 80, 90, 80);
INSERT INTO PERSON VALUES (PERSON_SEQ.NEXTVAL, '배수지', 20, 20, 90, 90);
INSERT INTO PERSON VALUES (PERSON_SEQ.NEXTVAL, '설수현', 20, 95, 95, 95);
INSERT INTO PERSON VALUES (PERSON_SEQ.NEXTVAL, '송혜교', 10, 100, 100, 100);
SELECT * FROM PERSON;

COMMIT;

-- 1) 데이터 입력
INSERT INTO PERSON VALUES (PERSON_SEQ.NEXTVAL, '송혜교', '배우', 100, 100, 100);

-- 2) 직업명
-- 검색, 성적 순 정렬
SELECT JNAME FROM JOB;
    
SELECT CONCAT(ROWNUM, '등') RN  , A.*
    FROM (SELECT PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT TOTAL
    FROM JOB J, PERSON P WHERE J.JNO = P.JNO ORDER BY TOTAL DESC) A
    WHERE JNAME = '배우';

-- 3) 데이터베이스에 입력된 사람 전체를 조회 총점 순 정렬
SELECT JNAME FROM JOB;

SELECT CONCAT(ROWNUM, '등') RN, A.*
    FROM (SELECT PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT TOTAL
        FROM JOB J, PERSON P WHERE J.JNO = P.JNO ORDER BY TOTAL DESC) A;



