-- Ex01. 부서번호를 받고 부서정보를 출력
SELECT * FROM DEPT WHERE DEPTNO = 40;
-- Ex02. 부서번호를 받고 부서정보와 사원정보를 출력
	-- (사번, 이름, 급여, 상사이름)
SELECT W.EMPNO, W.ENAME WORKER , W.SAL, M.ENAME MANAGER
	FROM EMP W, EMP M
	WHERE W.MGR = M.EMPNO AND W.DEPTNO = 10;
	
SELECT * FROM EMP WHERE DEPTNO = 10;

SELECT W.EMPNO, W.ENAME WORKER , W.SAL, M.ENAME MANAGER
	FROM EMP W, EMP M
	WHERE W.MGR = M.EMPNO;
-- Ex03

-- Ex04